# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

project_name: fvm
before:
  hooks:
    # you may remove this if you don't use vgo
    # - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
  goarch:
    - 386
    - amd64
    - arm
    - arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
brew:
  name: fvm
  github:
    owner: leoafarias
    name: homebrew-tap
  folder: Formula
  description: "Flutter version management tool"
  homepage: "https://github.com/leoafarias/fvm"
  dependencies:
    - git
  install: |
    bin.install "fvm"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^skip:'
