sudo: required
language: go
go: '1.10'
# services:
#   - docker
install:
  # - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true