name: fvm
description: A simple cli to manage Flutter SDK versions per project. Support channels, releases, and local cache for fast switching between versions.
version: 0.7.1
homepage: https://github.com/leoafarias/fvm

environment:
  sdk: ">=2.5.0 <3.0.0"

executables:
  fvm: main

dependencies:
  args: ^1.5.2
  cli_util: ^0.1.3+2
  # file_utils: ^0.1.3
  console: ^3.1.0
  io: ^0.3.3
  path: ^1.6.4

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  test_coverage: ^0.3.0
  build_runner: ^1.0.0
  build_version: ^2.0.1
