name: fvm
description: A simple version manager for Flutter.
version: 0.0.1
homepage: https://github.com/leoafarias/fvm
author: Leo Farias <leokcta@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
    args: ^1.5.2
    cli_util: ^0.1.3+2
    # file_utils: ^0.1.3
    console: ^3.1.0
    io: ^0.3.3
    path: ^1.6.4
  

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
