name: fvm
description: A simple cli to manage Flutter SDK versions per project. Support channels, releases, and local cache for fast switching between versions.
version: 2.0.0-dev.2
homepage: https://github.com/leoafarias/fvm

environment:
  sdk: ">=2.6.0 <3.0.0"

executables:
  fvm: main

dependencies:
  meta: ^1.3.0
  pubspec_yaml: ^2.0.1+1
  args: ^1.6.0
  cli_util: ^0.3.0
  console: ^3.1.0
  io: ^0.3.4
  path: ^1.7.0
  process_run: ^0.11.2+8
  http: ^0.12.2
  date_format: ^2.0.2
  version: ^2.0.0
  pub_api_client: ^1.0.9
  
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.15.7
  test_coverage: ^0.5.0
  build_runner: ^1.10.0
  build_version: ^2.0.2
  build_test: ^1.2.2
  grinder: ^0.8.6
  cli_pkg: ^1.2.0
 


