# This is a basic workflow that is manually triggered

name: Homebrew Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  deploy:
    name: Deploy Homebrew
    runs-on: ubuntu-latest
    env:
      PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
      GITHUB_TOKEN: ${{ secrets.HOMEBREW_FVM_GH_TOKEN }}
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: pub get


      - name: Build Version Number
        run: pub run build_runner build --delete-conflicting-outputs
        
      - name: Test 
        run: pub run test

      - name: Deploy to Homebrew
        run: pub run grinder pkg-homebrew-update

      